### ISSUE TITLE
Request 560201 returned to status F

### ISSUE THREAD

**Issue by zafar2zafar** [flexpeace/DI-Testing#20] opened 2016-02-08 11:36 UTC
I hit complete, land to Order Detail form, asks me to enter Comm. Type, added, and hit OK and it says "Request 560201 returned to status F". 

![Uploading error.jpg…]()

**Comment by samibrix** [comment] 2016-02-10 09:48
This error message pops up when trying to backup or cancel out of Modifying Order Details without filling in the required fields and the reason the MOD pops up is because the ordering physician never completed the required details and submitted the order as is.

**Comment by zafar2zafar** [comment] 2016-02-23 06:38
This error stopped the MRI workflow twice yesterday. It was understood that if Radiologist orders in PowerChart then this error occurs due to some fields mismatch. It turned out now that if a Physician (i.e. Obstetrician) who might have additional role as Radiologist can also produce this error. This needs to fixed on permanent basis. It is a real real showstopper OR are your sure that No Physician will have Radiologists rights when it goes live? I doubt that.

**Comment by fareedpax** [comment] 2016-02-23 06:46
Please.. let me understand the steps here as I was unaware of this error before.
I will connect with Zafar offline to discuss this.

**Comment by samibrix** [comment] 2016-02-24 10:42
This problem will accrue over and over again if we are not following the proper workflow in which physicians NOT radiologist or like radiologist prev order out of PowerChart reason being that we have added the contrast field that Avez requested, when using the radiologist to order the field doesn't display in PowerChart therefore when flowing to online work list it thinks that a field "mandatory field" is missing and it asks you to complete before moving on.

Zafar please follow the correct work flow in which a physician NOT radiologist or and physician with radiologist privileges order out of PowerChart. 
A radiologist SHOULD use DOE to order and not PowerChart.

**Comment by samibrix** [comment] 2016-02-24 10:47
The ONLY options for this is all physician will have radiologist privileges is to force them to use DOE to order in which this is not possible and not recommended or flex the contrast field to be mandatory in PowerChart in which physicians will not know what it means so the best way is to follow the proper work flow by having physician order then Radiologist vet and fill in the missing mandatory field which is the contrast + the scheduling fields to make sure tech won't see this once starting the order.

**Comment by zafar2zafar** [comment] 2016-02-28 07:22
This is 100% out of question, at least for me, that a physician cant have radiologist role. Anyways not concerned about that, if you guys are okay. 
What about this now? Ordering physician is PhysicianPediatrician1, Sidra UP 2015 - vetted by Radio1, Started by Ruth Lee, but she completes - the F error comes up. You can see Laura Wheelan patient now. 
**The F error comes WHEN a Tech tries to complete exam AND order details comes up. **
![f error](https://cloud.githubusercontent.com/assets/7323065/13377984/934ffb02-de04-11e5-8565-46fc3b11980f.jpg)

**Comment by fareedpax** [comment] 2016-02-28 07:25
Hi All,

 I did a test with the following real accounts :

echan : Radiologist with physician priveleges ( No tech priveleges!)
fahmed : Tech with no physician priveleges.

echan  placed orders on PowerChart .

I was able to start/complete without any errors.

We need more tests!!!

**Comment by zafar2zafar** [comment] 2016-02-28 07:30
Thanks Fareed. That means the reason of F error is something else, coz its still there unfortunately and when it occurs it hangs whole system and user have no choice but to kill the processes. 
How about above REAL patient? We are having F error and we cannot complete it. Patient needs to be reported. Can you please trouble shoot it?

**Comment by fareedpax** [comment] 2016-02-28 07:30
Hi All,

Can we not use "Radio1" account for a while .
Either use "UPRRAD1" or a real radiologist.

**Comment by fareedpax** [comment] 2016-02-28 07:42
OK.
A few more tests with real accounts.

Dr. A Hijazi - Cardiologist  -  Orders from Powerchart
echan - Radiologist  - Vets from Radnet Desktop
fahmed - Technologist   - Completes from citrix - Online W/L - Exam
management. -

No errors.


For the real patient.
Do you know any details that I will have to put in during the tech
completion ?

**Comment by genecs88** [comment] 2016-03-02 09:21
Update:
This issue has been resolved by modifying Privs for the Tech.
We are now conducting a root cause analysis.
Please test and close.

**Comment by zafar2zafar** [comment] 2016-03-06 11:49
Thanks. Solved so far. 
But a simple Tech might create it at some point. 
You are right, its actually a User-rights issue.

**Comment by avezrizvi** [comment] 2016-03-16 16:57
I'm closing out for now. If situation arises, please reopen issue.

**Closed by avezrizvi** 2016-03-16 16:57 UTC
Labels: bug, Priority 1, Ready To Test
